### ISSUE TITLE
Isn't working custom_header descriptor in envoy filter local rate limit

### ISSUE THREAD

**Issue by iliusa77** [brainfair/istio-ratelimits#10]
Hello,
I have Istio 1.23
Configured envoy filter by analogy with yours https://github.com/brainfair/istio-ratelimits/blob/main/httpbin-local-ratelimit/envoy-filter-rate-limit.yaml
But isn't working this section
```
                descriptors:
                  - entries:
                      - key: header_match
                        value: header_path
                      - key: custom_header
                        value: "111"
                    token_bucket:
                      max_tokens: 2
                      tokens_per_fill: 2
                      fill_interval: 10s
```
in the same time global token_bucket settings are working (if I change value 2147483647 to 2, I get 4 statuses 200 in replays and all other 429)

My EnvoyFilter configuration is the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hello-world
  namespace: default
spec:
  workloadSelector:
    labels:
      app: hello-world
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|5000"
            route:
              action: ROUTE
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                  - header_value_match:
                      descriptor_value: "header_path"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /ratelimit/test/
                            ignore_case: true
                  - request_headers:
                      header_name: custom-header
                      descriptor_key: custom_header
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 2147483647
                  tokens_per_fill: 2147483647
                  fill_interval: 10s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: "true"
                descriptors:
                  - entries:
                      - key: header_match
                        value: header_path
                      - key: custom_header
                        value: "111"
                    token_bucket:
                      max_tokens: 2
                      tokens_per_fill: 2
                      fill_interval: 10s
```

Test command the following:
```
for i in {1..6}; do curl -H "custom-header: 111" -s -k https://example.com/ratelimit/test/  -o /dev/null -w "%{http_code}\n"; sleep 0.1;done
200
200
200
200
200
200
```
expected output
```
200
200
200
200
429
429
```

Coul'd you suggest why this might not work, please.
